### ISSUE TITLE
Can it survive jpeg compression?

### ISSUE THREAD

**Issue by grez911** [desudesutalk/desudesutalk#16]
Some sites compress jpeg pictures after uploading. Can steganography message stays readable in that case?
I know, that this script works only on imageboards where compression usually is not performing, but theoretically, is it possible?

**Comment by desudesutalk** [comment]
[Algorithm used in DDT](https://code.google.com/p/f5-steganography/) will not survive any type of image changes (crop, resize, rotation, recompression) - this will kill hidden message. But this algorithm has big capacity (about 10% of original file size).

There are other algos (like digital watermarking) which can survive many changes in image, but their capacity is very small.
