### ISSUE TITLE
Скрипт не работает без userscript-движка

### ISSUE THREAD

**Issue by aslian** [desudesutalk/desudesutalk#25]
При попытке внедрить в страницу например этим
```
(function(src) {
    var elem = document.createElement('script');
    elem.setAttribute('type', 'text/javascript');
    elem.setAttribute("src", src);
    if (typeof(elem) !== 'undefined') document.getElementsByTagName('head')[0].appendChild(elem);
})('https://rawgit.com/desudesutalk/desudesutalk/master/ddt.user.js')
```
Ничего не произойдет, т.к. скрипт полагается на функцию `GM_getMetadata()`
https://github.com/desudesutalk/desudesutalk/search?utf8=%E2%9C%93&q=GM_getMetadata

Там вообще какое-то странное условие
```
(typeof GM_info !== 'undefined' ? GM_info.script.version : GM_getMetadata("version"))
```
Ни GM_info ни GM_getMetadata не определены в обычных браузерах. Предллагаю просто не выводить элемент с версией в таком случае. Ну или зашивать при сборке скрипта, как делает кукла. Кукла работает без движка юзерскрипта. Поправь пожалуйста.

Кстати, что там вообще с мобильной версией? На gh pages пусто, что за ddt_mobil.user.js, я так и не понял как это использовать.

**Comment by aslian** [comment]
Может там ещё что-то завязано на GM? По крайней мере логин работал и посты расшифровывались.

**Comment by desudesutalk** [comment]
> Ни GM_info ни GM_getMetadata не определены в обычных браузерах.

`GM_getMetadata` это обломок Скриптиша. А так как в скриптише ДДТ в принципе не работает, то можно и выпилить.

> Кстати, что там вообще с мобильной версией?

Её никто так и не стал делать.

> что за ddt_mobil.user.js, я так и не понял как это использовать.

Ставишь [яндексбраузер](https://play.google.com/store/apps/details?id=com.yandex.browser.beta&hl=ru), накатываешь на него Тамперманки и уже потом ставишь эту версию - будет как на десктопе почти.
