### ISSUE TITLE
/layer/ needs your help №2

### ISSUE THREAD

**Issue by bluche** [desudesutalk/desudesutalk#27]
Не знаю почему предыдущую issue отменили, но у нас проблемы. Надо что-то там изменить в CSP (Content Security Policy, насколько я понял) чтобы DDT правильно работал. Ты хоть видел что там с лэйнчаном творится? Ой-вей!

**Comment by desudesutalk** [comment]
Да, видел. Несколько раз писал им туда в /q/ что всё сломалось. Написал ещё раз.

**Comment by bluche** [comment]
Вижу что интерфейс работает, отлично. 
Слушай, а как с тобой ещё можно связаться, кроме гитхаба? Я хотел бы поговорить в более приватном месте.

**Comment by desudesutalk** [comment]
Да, заработало.

Можешь мне директ в [оффициальном треде](https://lainchan.org/layer/res/12.html) написать.
